package de.misi.idea.plugins.junit5helper.intentions

class RemoveDisplayNameFromMethodInjection : AbstractRemoveAnnotationIntention(ANNOTATION_DISPLAY_NAME, REMOVE_DISPLAY_NAME_FROM_METHOD, ::modifierListFromParentMethod)