package de.misi.idea.plugins.junit5helper.intentions

class RemoveDisabledFromMethodIntention : AbstractRemoveAnnotationIntention(ANNOTATION_DISABLED, REMOVE_DISABLED_FROM_METHOD, ::modifierListFromParentMethod)